image: node:11.15

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
  - node_modules/

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CI_SOURCE_IMAGE_WITH_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  DOCKER_DRIVER: overlay2

stages:
  - compile
  - build
  - deploy
  - cleanup
compile:
  stage: compile
  image: node:11.15
  dependencies: []
  variables:
  artifacts:
    expire_in: 30 mins
    paths:
      - dist
  before_script:
    - npm install -g gulp@4.0.0
    - npm install
    - gulp -v
    - node -v
  script:
    - gulp build
  allow_failure: false
  only:
    - branches
  tags:
    - docker
spawn:
  stage: build
  image: docker:dind
  dependencies:
    - compile
  services:
  variables:
  before_script:
  script:
    - |
      cat <<EOF > Dockerfile
      FROM nginx:alpine
      WORKDIR /var/www
      RUN mkdir -p /var/www
      RUN sed -i 's#root   /usr/share/nginx/html#root /var/www#' /etc/nginx/conf.d/default.conf
      COPY dist /var/www
      EOF
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_SOURCE_IMAGE_WITH_TAG || true
    - docker build
        --cache-from $CI_SOURCE_IMAGE_WITH_TAG
        --tag $CI_SOURCE_IMAGE_WITH_TAG .
    - docker push $CI_SOURCE_IMAGE_WITH_TAG
  allow_failure: false
  only:
    - branches
  tags:
    - docker
deploy_review:
  image: docker:dind
  stage: deploy
  dependencies:
    - spawn
  variables:
    DOCKER_HOST: tcp://192.168.0.224:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs"
    REVIEW_HOST: ${CI_PROJECT_PATH_SLUG}-${CI_COMMIT_REF_SLUG}.${REVIEW_DOMAIN}
  script:
    - mkdir -p $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker stack deploy -c docker-compose.swarm.yml $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG --with-registry-auth --resolve-image=always --prune
    - rm -rf $DOCKER_CERT_PATH
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url:  https://${CI_PROJECT_PATH_SLUG}-$CI_COMMIT_REF_SLUG.$REVIEW_DOMAIN
    on_stop: stop_review
  when: manual
  only:
    - branches
  tags:
    - docker
stop_review:
  image: docker:dind
  stage: cleanup
  dependencies:
    - deploy_review
  script:
    - mkdir -p $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
    - docker stack rm $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
    - rm -rf $DOCKER_CERT_PATH
  variables:
    DOCKER_HOST: tcp://192.168.0.224:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs"
    GIT_STRATEGY: clone
  when: manual
  environment:
      name: review/$CI_COMMIT_REF_NAME
      action: stop
  only:
      - branches
  tags:
  - docker
